[project]
name = "hitl-0231-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=6.29.1",
    "openai-agents==0.23.1",
    "python-dotenv>=1.2.4",
]

[project.scripts]
hitl-0231-test = "hitl_0231_test:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
