[project]
name = "crewai_memory"
version = "0.1.0"
description = "crewai_memory using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=1.15.22,<2.0.0"
]

[project.scripts]
crewai_memory = "crewai_memory.main:run"
run_crew = "crewai_memory.main:run"
train = "crewai_memory.main:train"
replay = "crewai_memory.main:replay"
test = "crewai_memory.main:test"
run_with_trigger = "crewai_memory.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
project_id = "562e1b5d-f551-45c1-8600-922844854322"
